spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/mdd}
spring.datasource.username=${DB_USERNAME:mdd}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

spring.flyway.enabled=true

server.port=${SERVER_PORT:9000}
app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN:http://localhost:4200}
